version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000    
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  redis:
    image: redis
    command: redis-server --save '' --appendonly 'no'

  nginx:
    container_name: nginx_server
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/var/www/html/static
    depends_on:
      - web
    ports:
      - "0.0.0.0:80:80"